name: Build Android APK

on:
  # وقتی شما دستی این کار را شروع می‌کنید
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت کدها (Checkout)
        uses: actions/checkout@v4

      - name: راه اندازی جاوا (Java)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: راه اندازی فلاتر (Flutter)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # یا نسخه مورد نظر شما
          channel: 'stable'

      - name: نصب کتابخانه‌ها (Pub Get)
        run: flutter pub get

      - name: ساخت فایل APK (Build)
        run: flutter build apk --release

      - name: آپلود فایل نهایی (Upload Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
